In [1]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('ml_data/classification_data.csv')
data.head()

BookID   Raters  Reviewers  Pages  PublishYear  review
0       1  2469197      40043  652.0         2005       2
1       2  2541611      43067  870.0         2003       2
2       3  7145889     113905  309.0         1997       2
3       4  2766218      53651  352.0         1998       2
4       5  2849671      56337  435.0         1999       2

In [3]:
info = data[['Raters', 'Reviewers', 'Pages', 'PublishYear']]
labels = data.review

In [6]:
info_train, info_test, labels_train, labels_test = train_test_split(info, labels, train_size = 0.8, test_size = 0.2, random_state=42)

classifier = GaussianNB()
classifier.fit(info_train, labels_train)

predict = classifier.predict(info_test)

In [7]:
test_labels = labels_test.values.tolist()

result_matrix = np.zeros((3, 3), dtype='int32')
correct = 0

for i in range(len(test_labels)):
    result_matrix[test_labels[i]][predict[i]] += 1
    
    if predict[i] == test_labels[i]:
        correct += 1

print(result_matrix)
print(correct/len(test_labels))

[[ 241   26    7]
 [4492 1019  338]
 [8279 3324 1795]]
0.1564981302187388
